// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3hDWBbCINLNr0N1SLl-NASPABoGR3vIw',
    appId: '1:40853127436:web:99086bbe6f01c8bf5c0929',
    messagingSenderId: '40853127436',
    projectId: 'authentication-login-e8761',
    authDomain: 'authentication-login-e8761.firebaseapp.com',
    storageBucket: 'authentication-login-e8761.appspot.com',
    measurementId: 'G-F7FW9Q8FDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Rhn2WfLDbOiJ7PgpvB_VuughURnKL_s',
    appId: '1:40853127436:android:05271bd243c0b6a45c0929',
    messagingSenderId: '40853127436',
    projectId: 'authentication-login-e8761',
    storageBucket: 'authentication-login-e8761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1QCSLX7g8ZDNCQ386W7sN8gPON_acIo',
    appId: '1:40853127436:ios:451bdac66721eab85c0929',
    messagingSenderId: '40853127436',
    projectId: 'authentication-login-e8761',
    storageBucket: 'authentication-login-e8761.appspot.com',
    androidClientId: '40853127436-dkeni5bfn3qbuqaptrar9nm1j4dj1p15.apps.googleusercontent.com',
    iosClientId: '40853127436-79of39k20fidpk8v7lh28i5r700ptuhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.exploraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI1QCSLX7g8ZDNCQ386W7sN8gPON_acIo',
    appId: '1:40853127436:ios:57a6418e804911bc5c0929',
    messagingSenderId: '40853127436',
    projectId: 'authentication-login-e8761',
    storageBucket: 'authentication-login-e8761.appspot.com',
    androidClientId: '40853127436-dkeni5bfn3qbuqaptrar9nm1j4dj1p15.apps.googleusercontent.com',
    iosClientId: '40853127436-c782rjfudp0fmmk9gml2noh5g5gd3jld.apps.googleusercontent.com',
    iosBundleId: 'com.example.exploraApp.RunnerTests',
  );
}
